version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rating_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./.env-non-dev
    networks:
      - rating_network

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A rating beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    env_file:
      - ./.env-non-dev
    networks:
      - rating_network

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A rating worker --loglevel=info --pool=solo
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - celery_beat
    env_file:
      - ./.env-non-dev
    networks:
      - rating_network

  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flower
    command: celery -A rating flower --port=5555
    ports:
      - "5556:5555"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - celery_worker
    env_file:
      - ./.env-non-dev
    networks:
      - rating_network

  web:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"

volumes:
  redis_data:

networks:
  rating_network:
    driver: bridge
