# Generated by Django 5.1.6 on 2025-02-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Бронза', 'Бронза'), ('Серебро', 'Серебро'), ('Золото', 'Золото'), ('Алмаз', 'Алмаз'), ('Джедай', 'Джедай')], default='Бронза', max_length=7, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('call_sign', models.CharField(max_length=100, unique=True)),
                ('orders_count', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('up', 'up'), ('remain', 'remain'), ('down', 'down')], default='remain', max_length=7, verbose_name='Грейд')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peoples', to='main.rank', verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
