# Generated by Django 5.1.6 on 2025-02-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_people_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rank/images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='rank',
            name='prize',
            field=models.PositiveIntegerField(default=0, verbose_name='Приз'),
        ),
    ]
