# Generated by Django 5.1.6 on 2025-02-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rank_image_rank_prize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-orders_count'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['prize'], 'verbose_name': 'Звание', 'verbose_name_plural': 'Звания'},
        ),
        migrations.AddField(
            model_name='rank',
            name='orders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
    ]
