# Generated by Django 5.1.6 on 2025-02-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_people_options_alter_rank_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='rank/images/', verbose_name='Изображение'),
        ),
    ]
